solution/IVV.Website/Controllers/WebsiteController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using IVV.Website.ClassLib;
using IVV.Website.DataModel;

namespace IVV.Website.Controllers {

	[AllowAnonymous]
	public class WebsiteController : Controller {

		

		IVV.Website.DataModel.SiteEntity context;

		public WebsiteController() {
			context = new DataModel.SiteEntity();
		}

		protected override void OnActionExecuted(ActionExecutedContext filterContext) {
			var ck = "Http500ErrMsg";
			if (filterContext.Exception != null) {
				var internalError = 
					string.Format("<div>{0}</div><div>{1}</div>",filterContext.Exception.Message,filterContext.Exception.StackTrace);
				if (HttpRuntime.Cache[ck] != null) {
					HttpRuntime.Cache.Remove(ck);
				}
				HttpRuntime.Cache.Insert(ck, internalError);
				filterContext.HttpContext.Response.Redirect("/error.aspx");
			}

		}
		protected override void OnResultExecuted(ResultExecutedContext filterContext) {
			var ck = "Http500ErrMsg";
			if (filterContext.Exception != null) {
				var internalError = 
					string.Format("<div>{0}</div><div>{1}</div>",filterContext.Exception.Message,filterContext.Exception.StackTrace);
				
				if (HttpRuntime.Cache[ck] != null) {
					HttpRuntime.Cache.Remove(ck);
				}

				HttpRuntime.Cache.Insert(ck, internalError);
				
				filterContext.HttpContext.Response.Redirect("/error.aspx");

				
			}

		}


		public ActionResult Index() {
			return Redirect("~/index.html");
		}
		public ActionResult Error() {
			var ck = "Http500ErrMsg";
			if (HttpRuntime.Cache[ck] != null) {
				ViewData[ck] = HttpRuntime.Cache[ck];
					HttpRuntime.Cache.Remove(ck);
				}
			return View();
		}
		public ActionResult Product() {
			return View("Product");
		}

		public ActionResult Menu(string name) {
			ViewBag.Selected = name;
			return View("_Menu");
		}

		public ActionResult ProductList(string s,string type,int? c,string sc,string color) {
			var cateList = context.ProductCategory.Where(t => t.ParentId == null);
			if (!string.IsNullOrEmpty(s)) {
				var si = IVV.Website.ClassLib.EnumHelper.GetEnumKey<IVV.Website.ClassLib.ProductSeries>(s);
				cateList = cateList.Where(t => t.Series == si);
			}
			var m = new IVV.Website.Models.ProductModel();

			m.CategoryList = cateList;
			var subCates = new List<string>();
			context.Product.Select(t => new { Sn = t.SubCategory, Cid = t.CategoryId })
							.Distinct().ForEach(a => {
								subCates.Add(string.Format("{0}*$*{1}",a.Cid,a.Sn));
							});
			m.SubCategoryList = subCates;
			m.ColorList = context.Product.Select(t => t.Color).Distinct().ToList();

			if (type == "in") {
				var plist = context.Product.AsQueryable();
				if (c.HasValue) {
					plist = plist.Where(t => t.CategoryId == c.Value);
				}
				if (!string.IsNullOrEmpty(sc)) {
					plist = plist.Where(t => t.SubCategory == sc);
				}
				if (!string.IsNullOrEmpty(color)) {
					plist = plist.Where(t => t.Color == color);
				}
				m.ProductList = plist;
				m.ColorList = plist.Select(t => t.Color).Distinct().ToList();
			}
			return View(m);
		}

		public ActionResult ProductItem(string s,string type,int? c,int id) {
			var cateList = context.ProductCategory.Where(t => t.ParentId == null);
			if (!string.IsNullOrEmpty(s)) {
				var si = IVV.Website.ClassLib.EnumHelper.GetEnumKey<IVV.Website.ClassLib.ProductSeries>(s);
				cateList = cateList.Where(t => t.Series == si);
			}
			var m = new IVV.Website.Models.ProductModel();

			m.CategoryList = cateList;
			var subCates = new List<string>();
			context.Product.Select(t => new { Sn = t.SubCategory, Cid = t.CategoryId })
							.Distinct().ForEach(a => {
								subCates.Add(string.Format("{0}*$*{1}",a.Cid,a.Sn));
							});
			m.SubCategoryList = subCates;
			m.ColorList = context.Product.Select(t => t.Color).Distinct().ToList();

			if (type == "in" && c.HasValue) {
				m.ProductList = context.Product.Where(t => t.CategoryId == c.Value);
			}
			m.Item = context.Product.SingleOrDefault(t => t.Id == id);
			
			return View(m);
		}

		public ActionResult Maintenance() {
			return View("Maintenance");
		}

		public ActionResult Company() {
			var m = context.SiteInfo.First();
			return View(m);
		}

		public ActionResult News(int? pageIndex) {
			pageIndex = pageIndex ?? 1;

			var list = context.Post.AsQueryable();
            
			

            ViewData["list"] = new PageList<Post>( list.OrderByDescending(t => t.Id).ThenByDescending(t => t.CreateDate)
													, pageIndex.Value,10);

            
            ViewData["pageIndex"] = pageIndex;

            return View();
		}

		public ActionResult ReadNews(int id) {
			var m = context.Post.SingleOrDefault(t => t.Id == id);
			return View(m);
		}

		public ActionResult Download() {
			return View("Download");
		}

		public ActionResult Video(int? pageIndex) {
			pageIndex = pageIndex ?? 1;

			var list = context.Video.AsQueryable();
            ViewData["list"] = new PageList<Video>( list.OrderByDescending(t => t.Id)
													, pageIndex.Value,10);
            ViewData["pageIndex"] = pageIndex;
            return View();
		}

		public ActionResult Gallery() {
			return View("Gallery");
		}

		public ActionResult Contact() {
			var m = new NoteBook();
			return View(m);
		}

		[HttpPost]
		public ActionResult Contact(NoteBook model) {
			model.CreateDate = DateTime.Now;
			object imgCode = Session["ImgCode"];

			if (imgCode.ToString() != model.ValCode.ToUpper()) {
				ModelState.AddModelError("ValCode", "验证码输入有误");
			}

			if (!ModelState.IsValid) { 
				return View();
			}
			try {
				context.NoteBook.Add(model);
				context.SaveChanges();
				TempData["SuccessMsg"] = "提交成功！我们将在第一时间和您联系！";
			}
			catch (Exception ex) {
				ModelState.AddModelError("DbError", ex.Message);
				return View();
			}

			return RedirectToAction("Contact");
			
		}

		public ActionResult Stores() {
			return View("Stores");
		}

	}
}

solution/IVV.Website/Views/Website/Company.cshtml
@model IVV.Website.DataModel.SiteInfo
@{
    ViewBag.Title = "Company";
}

@section menu{
	@Html.Action("Menu", "Website", new { name = "公司介绍" })
}

<h1>公司介绍</h1>
@Html.Raw(Model.Company)

solution/IVV.Website/Views/Website/Contact.cshtml
@model IVV.Website.DataModel.NoteBook
@{
    ViewBag.Title = "联系我们";
    Layout = "~/Views/Website/_LayoutList.cshtml";
}


@section head{
<style type="text/css">
body {
	background-image: url(images/dettaglio-niagara.jpg);
}
#content {
	font-size:12px;
}

table td {
	padding:6px 0 5px;
}

.textBox {
	border:1px solid #eaeaea;
	background:url(images/input_bg.png) left top repeat;
	padding:4px;
	font-size:14px;
	width:280px;
}
    textarea.msg
    {
        width:280px;height:80px;
    }
    .must
    {
        color:#b94a48;
    }
</style>
    <script src="/Scripts/jquery-ui-1.10.2/jquery-1.9.1.js"></script>
    <script type="text/javascript" src="/Scripts/jquery.validate-vsdoc.js"></script>
    <script type="text/javascript" src="/Scripts/jquery.validate.min.js"></script>
    <script type="text/javascript" src="/Scripts/jquery.validate.unobtrusive.min.js"></script>
    <script type="text/javascript" src="/Scripts/jquery.unobtrusive-ajax.min.js"></script>
}

@section menu{
	@Html.Action("menu", "Website", new { name="联系我们" })
}

<h1>联系我们</h1>
<br /><br />

<p><strong>Opening hours</strong></p>
<p>Monday: 16.00-20.00<br />
    Tuesday - Saturday: 9.00-13.00 16.00-20.00<br />
</p><br />

<div><p><strong>IVV SHOP</strong><br />
Lungarno Guido Reni n.60 San Giovanni V.no (AR)<br />
Phone + 39.055.942619</p>
</div>
<br />
<div>
<p><strong>IVV OUTLET Design Outlet Italiano - welcHome Santhi&agrave;</strong><br />
Corso 25 Aprile, Loc. Moleto Sud, Santhi&agrave; (VC) </p>
</div>

<br /><br /><br />
@using(Html.BeginForm()) {
	<table>
		<tr>
			<td style="width:120px;">姓名: </td>
			<td>
                @Html.EditorFor(model => model.Name)<span class="must"> *</span>
                @Html.ValidationMessageFor(model => model.Name)
			</td>
		</tr>
		
		<tr>
			<td>公司:</td>
			<td>
                @Html.EditorFor(model => model.Company)
                @Html.ValidationMessageFor(model => model.Company)
			</td>
		</tr>
		<tr>
			<td>国家:</td>
			<td>
                @Html.EditorFor(model => model.Country)
                @Html.ValidationMessageFor(model => model.Country)
			</td>
		</tr>
		<tr>
			<td>手机:</td>
			<td>
                @Html.EditorFor(model => model.Phone)<span class="must"> *</span>
                @Html.ValidationMessageFor(model => model.Phone)
			</td>
		</tr>
		<tr>
			<td>E-mail:</td>
			<td>
                @Html.EditorFor(model => model.Email)<span class="must"> *</span>
                @Html.ValidationMessageFor(model => model.Email)
			</td>
		</tr>
		<tr>
			<td valign="top">留言:</td>
			<td>
                @Html.TextAreaFor(model => model.Message, new { @class="msg"})<span class="must"> *</span>
                @Html.ValidationMessageFor(model => model.Message)
			</td>
		</tr>
		<tr>
			<td>验证码:</td>
			<td>
				
				@Html.EditorFor(model => model.ValCode)<span class="must"> *</span>
                
                <img id="imgCoder" src="~/Service/CheckImage.aspx" alt="" 
					title="看不清楚？点击换一张"  />
                <br />
                @Html.ValidationMessageFor(model => model.ValCode)
			</td>
		</tr>
        <tr>
            <td></td>
            <td>
                <button type="submit" style="background:url(/images/form_send.png);width:85px;height:30px;">&nbsp;&nbsp;&nbsp;</button>
            </td>
        </tr>
	</table>
}

<script type="text/javascript">
    $("#imgCoder").click(function () {
        $(this).attr("src",
            "@Url.Content("~/Service/CheckImage.aspx?rnd=")" + Math.random());
    });
    @if (TempData["SuccessMsg"] != null) { 
        @:alert("@TempData["SuccessMsg"]");
    }
</script>





solution/IVV.Website/Views/Website/Gallery.cshtml
@{
    ViewBag.Title = "画册";
    Layout = "~/Views/Website/_LayoutList.cshtml";
}

@section menu{
	@Html.Action("menu", "Website", new { name = "画册" })
}

@section head{
<link href="~/Scripts/Slider/slider.css" rel="stylesheet" />
<style type="text/css">
body {
	background-image: url(images/dettaglio-magnolia.jpg);
}
</style>
}

<h1>画册</h1>
<div id="slider-container1">
    
    <div class="sl_images">
<a href="#"><img src="http://www.ivvnet.it/photogallery/01.jpg" id="img0" title="One"/></a>
<a href="#"><img src="http://www.ivvnet.it/photogallery/02.jpg" id="img1" title="Tessuti"/></a>
<a href="#"><img src="http://www.ivvnet.it/photogallery/03.jpg" id="img2" title="Multicolor"/></a>
<a href="#"><img src="http://www.ivvnet.it/photogallery/04.jpg" id="img3" title="Multicolor"/></a>
<a href="#"><img src="http://www.ivvnet.it/photogallery/05.jpg" id="img4" title="Multicolor"/></a>
<a href="#"><img src="http://www.ivvnet.it/photogallery/06.jpg" id="img5" title="Mon Amour"/></a>
<a href="#"><img src="http://www.ivvnet.it/photogallery/07.jpg" id="img6" title="Magnolia"/></a>
<a href="#"><img src="http://www.ivvnet.it/photogallery/08.jpg" id="img7" title="Aria"/></a>
<a href="#"><img src="http://www.ivvnet.it/photogallery/09.jpg" id="img8" title="Vizio"/></a>
<a href="#"><img src="http://www.ivvnet.it/photogallery/10.jpg" id="img9" title="Special"/></a>
<a href="#"><img src="http://www.ivvnet.it/photogallery/11.jpg" id="img10" title="Special"/></a>
<a href="#"><img src="http://www.ivvnet.it/photogallery/12.jpg" id="img11" title="Special"/></a>
<a href="#"><img src="http://www.ivvnet.it/photogallery/13.jpg" id="img12" title="Roseto"/></a>
<a href="#"><img src="http://www.ivvnet.it/photogallery/14.jpg" id="img13" title="Primula"/></a>
<a href="#"><img src="http://www.ivvnet.it/photogallery/15.jpg" id="img14" title="Bisanzio"/></a>
<a href="#"><img src="http://www.ivvnet.it/photogallery/16.jpg" id="img15" title="Multicolor"/></a>
<a href="#"><img src="http://www.ivvnet.it/photogallery/17.jpg" id="img16" title="Multicolor"/></a>
<a href="#"><img src="http://www.ivvnet.it/photogallery/18.jpg" id="img17" title="Monamour"/></a>
<a href="#"><img src="http://www.ivvnet.it/photogallery/19.jpg" id="img18" title="Monamour"/></a>
<a href="#"><img src="http://www.ivvnet.it/photogallery/20.jpg" id="img19" title="Menhir"/></a>
<a href="#"><img src="http://www.ivvnet.it/photogallery/21.jpg" id="img20" title="Loto"/></a>
<a href="#"><img src="http://www.ivvnet.it/photogallery/22.jpg" id="img21" title="Infiore"/></a>
<a href="#"><img src="http://www.ivvnet.it/photogallery/23.jpg" id="img22" title="Infiore"/></a>
<a href="#"><img src="http://www.ivvnet.it/photogallery/24.jpg" id="img23" title="diamantè"/></a>
<a href="#"><img src="http://www.ivvnet.it/photogallery/25.jpg" id="img24" title="diamantè"/></a>
<a href="#"><img src="http://www.ivvnet.it/photogallery/26.jpg" id="img25" title="diamantè"/></a>
<a href="#"><img src="http://www.ivvnet.it/photogallery/27.jpg" id="img26" title="diamantè"/></a>
<a href="#"><img src="http://www.ivvnet.it/photogallery/28.jpg" id="img27" title="diamantè"/></a>
<a href="#"><img src="http://www.ivvnet.it/photogallery/29.jpg" id="img28" title="diamantè"/></a>
<a href="#"><img src="http://www.ivvnet.it/photogallery/30.jpg" id="img29" title="diamantè"/></a>
<a href="#"><img src="http://www.ivvnet.it/photogallery/31.jpg" id="img30" title="diamantè"/></a>
<a href="#"><img src="http://www.ivvnet.it/photogallery/32.jpg" id="img31" title="Allinone"/></a>
<a href="#"><img src="http://www.ivvnet.it/photogallery/33.jpg" id="img32" title="Allinone"/></a>

</div><!--end sl_images-->
<div style="position:absolute; height:25px; width:100%; left:0; bottom:0; z-index:40;"></div>
<div class="sl_bullets">
  <div>
<a href="#img0" title=""><img src="http://www.ivvnet.it/photogallery/01s.jpg"/></a>
<a href="#img1" title=""><img src="http://www.ivvnet.it/photogallery/02s.jpg"/></a>
<a href="#img2" title=""><img src="http://www.ivvnet.it/photogallery/03s.jpg"/></a>
<a href="#img3" title=""><img src="http://www.ivvnet.it/photogallery/04s.jpg"/></a>
<a href="#img4" title=""><img src="http://www.ivvnet.it/photogallery/05s.jpg"/></a>
<a href="#img5" title=""><img src="http://www.ivvnet.it/photogallery/06s.jpg"/></a>
<a href="#img6" title=""><img src="http://www.ivvnet.it/photogallery/07s.jpg"/></a>
<a href="#img7" title=""><img src="http://www.ivvnet.it/photogallery/08s.jpg"/></a>
<a href="#img8" title=""><img src="http://www.ivvnet.it/photogallery/09s.jpg"/></a>
<a href="#img9" title=""><img src="http://www.ivvnet.it/photogallery/10s.jpg"/></a>
<a href="#img10" title=""><img src="http://www.ivvnet.it/photogallery/11s.jpg"/></a>
<a href="#img11" title=""><img src="http://www.ivvnet.it/photogallery/12s.jpg"/></a>
<a href="#img12" title=""><img src="http://www.ivvnet.it/photogallery/13s.jpg"/></a>
<a href="#img13" title=""><img src="http://www.ivvnet.it/photogallery/14s.jpg"/></a>
<a href="#img14" title=""><img src="http://www.ivvnet.it/photogallery/15s.jpg"/></a>
<a href="#img15" title=""><img src="http://www.ivvnet.it/photogallery/16s.jpg"/></a>
<a href="#img16" title=""><img src="http://www.ivvnet.it/photogallery/17s.jpg"/></a>
<a href="#img17" title=""><img src="http://www.ivvnet.it/photogallery/18s.jpg"/></a>
<a href="#img18" title=""><img src="http://www.ivvnet.it/photogallery/19s.jpg"/></a>
<a href="#img19" title=""><img src="http://www.ivvnet.it/photogallery/20s.jpg"/></a>
<a href="#img20" title=""><img src="http://www.ivvnet.it/photogallery/21s.jpg"/></a>
<a href="#img21" title=""><img src="http://www.ivvnet.it/photogallery/22s.jpg"/></a>
<a href="#img22" title=""><img src="http://www.ivvnet.it/photogallery/23s.jpg"/></a>
<a href="#img23" title=""><img src="http://www.ivvnet.it/photogallery/24s.jpg"/></a>
<a href="#img24" title=""><img src="http://www.ivvnet.it/photogallery/25s.jpg"/></a>
<a href="#img25" title=""><img src="http://www.ivvnet.it/photogallery/26s.jpg"/></a>
<a href="#img26" title=""><img src="http://www.ivvnet.it/photogallery/27s.jpg"/></a>
<a href="#img27" title=""><img src="http://www.ivvnet.it/photogallery/28s.jpg"/></a>
<a href="#img28" title=""><img src="http://www.ivvnet.it/photogallery/29s.jpg"/></a>
<a href="#img29" title=""><img src="http://www.ivvnet.it/photogallery/29s.jpg"/></a>
<a href="#img30" title=""><img src="http://www.ivvnet.it/photogallery/30s.jpg"/></a>
<a href="#img31" title=""><img src="http://www.ivvnet.it/photogallery/31s.jpg"/></a>
<a href="#img32" title=""><img src="http://www.ivvnet.it/photogallery/32s.jpg"/></a>
<a href="#img33" title=""><img src="http://www.ivvnet.it/photogallery/33s.jpg"/></a>
</div><!--end bullets-->

</div><!--end slider-container1-->
	
<script src="~/Scripts/Slider/slider.js"></script>

solution/IVV.Website/Views/Website/Maintenance.cshtml
@{
    ViewBag.Title = "产品保养";
    Layout = "~/Views/Website/_LayoutList.cshtml";
}

@section head{
<style type="text/css">
body {
	background-image: url(images/dettaglio-bouquet.jpg);
}
	#content {
		font-size:12px;
		font-family:Verdana;		
	}
</style>
}

@section menu{
	@Html.Action("Menu", "Website", new { name = "产品保养" })
}

<h1>产品保养</h1>

<h3 style="font-size:13px;color:#666;">Cleaning and maintenance instructionsfor IVV objects</h3>
 <p>&nbsp;</p>
<p><strong>DECORATION WITH GOLD/PLATINUM</strong>: <br />
Use a cloth, preferably microfibre (non-abrasive), damp it slightly and pass it over the surface. Dry it using a dry microfibre cloth.<br />
Note: the gold decoration may become tarnished in time due to exposure to the atmosphere (it tends to go red). Even in this case it can be cleaned following the procedure described above.<br />
Not microwave safe.</p>
<p>&nbsp;</p>
<p> <strong>SILVER DECORATION</strong>: <br />
  Use only specific silver polish products following carefully the instructions. <br />
  Not microwave safe.</p>
<p><br />
  <strong>TRANSPARENT, OPAQUE, PEARLY OR METALLIC INTERNAL AND/OR EXTERNAL COLOURING</strong>: <br />
  Use dishes neutral detergent. Rinse well with water and dry with a soft cloth, preferably microfibre. </p>
<p><br />
  <strong>GOLD OR SILVER LEAF DECORATION</strong>: <br />
  Use a cloth, preferably microfibre (non-abrasive), damp it slightly and pass it over the surface. Dry it using a dry microfibre cloth.<br />
  Not microwave safe.</p>
<p><br />
  <strong>DECORATION WITH CHROME</strong>: <br />
  Use dishes neutral detergents. Rinse well with water and dry with a soft cloth, preferably microfibre.</p>
<p> <br />
  <strong>SAND-BLASTED DECORATION</strong>: <br />
  se neutral detergents. Dry the object immediately after rinsing to avoid any trace of detergent that might cause stains. </p>
<p><br />
  <strong>SATIN FINISH</strong>: <br />
  Never use abrasive materials when cleaning. </p>
<p><br />
  <strong>MIRROR EFFECT</strong>: <br />
  (Glossy, satin or velvet finish) Wipe delicately using soft, non-abrasive and clean cloths. <br />
  Not microwave safe.</p>
<p><br />
  <strong>PLAIN GLASS OBJECTS</strong>: <br />
  Any glass detergent can be used. <br />
  To remove grease from glass, use water with a few drops of vinegar. </p>

solution/IVV.Website/Views/Website/News.cshtml
@{
    ViewBag.Title = "新闻";
    var list = ViewData["list"] as IVV.Website.ClassLib.PageList<IVV.Website.DataModel.Post>;
}

@section head{
<style type="text/css">
body {
	background-image: url(images/dettaglio-love.jpg);
}
</style>
}

@section menu{
	@Html.Action("Menu", "Website", new { name = "新闻" })
}

<h1>新闻</h1>



<table class="table">

    <thead>
        <tr>
            <th style="width:400px;">标题</th>
            <th>日期</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in list) {
        <tr>
            <td title="@item.Title">@Html.ActionLink(IVV.Website.ClassLib.StringExtentions.SubString(item.Title,22), "ReadNews", new { id = item.Id})</td>
            <td>@item.CreateDate.ToShortDateString()</td>
        </tr>
        }
        
    </tbody>
</table>
@{
var pars = new Dictionary<string, object>();
        
    Html.RenderPager("_PageBar", list.Count, 10, (int)ViewData["pageIndex"], "/news.aspx", pars);
}

<div class="clear"></div>

solution/IVV.Website/Views/Website/ReadNews.cshtml
@model IVV.Website.DataModel.Post
@{
    ViewBag.Title = "查看新闻";
}

@section head{
<style type="text/css">
body {
	background-image: url(images/dettaglio-love.jpg);
}
</style>
}

@section menu{
	@Html.Action("Menu", "Website", new { name = "新闻" })
}

<h1>@Model.Title</h1>

<div>
    <span>@Model.Poster</span>发表于<span>@Model.CreateDate.ToShortDateString()</span>

</div>

<p style="height:1px;background:#aaa;margin-bottom:20px;">
    @Html.Raw(Model.Content)
</p>

<br />



solution/IVV.Website/Views/Website/Stores.cshtml
@{
    ViewBag.Title = "商店";
    Layout = "~/Views/Website/_LayoutList.cshtml";
}


@section head{
<style type="text/css">
body {
	background-image: url(images/dettaglio-nuance.jpg);
}
</style>
}

@section menu{
	@Html.Action("menu", "Website", new { name="商店" })
}

<h1>商店</h1>

<br /><br />

Find IVV products near you

<table style="margin:1.5em 0 1.5em;">
	<tr>
		<td style="width:80px;padding-bottom:1.2em;">Country: </td>
		<td style="padding-bottom:1.2em;"><select style="background:#bbb;border:none;width:180px;"><option>China</option></select></td>
	</tr>
	<tr>
		<td>City:</td>
		<td><select style="background:#bbb;border:none;width:180px;"><option>Shenzhen</option></select></td>
	</tr>
</table>

<p style="line-height:140%;">
<strong>SWEET HOME </strong><br />
Via Vittorio Veneto 47/c <br />
Armento (PZ) <br />
Telephone: 0971751377<br />
</p>

solution/IVV.Website/Views/Website/Video.cshtml
@{
    ViewBag.Title = "Video";
    var list = ViewData["list"] as IVV.Website.ClassLib.PageList<IVV.Website.DataModel.Video>;
}


@section head{
    <script src="/Scripts/jquery-ui-1.10.2/jquery-1.9.1.js"></script>
	<script src="/Scripts/jquery-ui-1.10.2/ui/jquery-ui.js"></script>
	<link href="/Scripts/jquery-ui-1.10.2/themes/base/jquery.ui.all.css" rel="stylesheet" />
<style type="text/css">
body {
	background-image: url(images/dettaglio-dream.jpg);
}
</style>
}

@section menu{
	@Html.Action("menu", "Website", new { name="视频" })
}

<h1>视频</h1>

<div class="imgContainer">
    @foreach (var item in list) { 
    <p class="item">
        <span class="hide video">@Html.Raw(item.HtmlCode)</span>
        <img class="thumb" src="@item.ImgUrl" alt="@item.Title" /><br />
        <span title="@item.Title">@IVV.Website.ClassLib.StringExtentions.SubString(item.Title,10)</span>
    </p>
    }
</div>

<div class="clear"></div>

<div id="dialog"></div>

<script type="text/javascript">
    $(document).ready(function(){
        $("div.imgContainer p.item").click(function () {
            $("#dialog").html("");
            $("#dialog").append($(this).find("span.video").html());
            $("#dialog").dialog({
                autoOpen : true,
                title: "播放视频",
                width: 515,
                height:460
            });
        });
    });
</script>